name: mysimtek
description: "OFA Mobile"
publish_to: 'none'
version: 1.5.0+2

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  intl: ^0.19.0
  google_fonts: ^8.0.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.1.3
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  connectivity_plus: ^6.1.4
  path_provider: ^2.1.5
  gal: ^2.3.0
  pdf: ^3.11.0
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Cek versi terbaru di pub.dev

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_ofa_pelanggan.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_ofa_pelanggan_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/logo/
