// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0xuVlMTX5h_HEmaHvCXh7psfohaJkcCQ',
    appId: '1:294224939799:android:f6978b1164d5c78d8f4552',
    messagingSenderId: '294224939799',
    projectId: 'mysimtek-pelanggan',
    storageBucket: 'mysimtek-pelanggan.firebasestorage.app',
  );
}
